#! /bin/sh

uri=`cat ./repo`

echo 'make tmp_rpms dir'
rm -fr ./tmp_rpms
mkdir ./tmp_rpms

rm ARCHIVES*

echo 'start to get ARCHIVES.gz from' $uri
wget $uri'ARCHIVES.gz'
gunzip ARCHIVES.gz
echo 'get ARCHIVE'

echo 'start to generate ./meta'
grep "\.desktop" ARCHIVES  |  grep "/usr/share/app"  | awk  '{print $1 $10}'  > rpm-desktop
awk '{print $1}' ARCHIVES | grep -i hicolor-icon-theme | uniq | tr -d ':' >> meta
awk '{print $1}' ARCHIVES | grep -i gnome-icon-theme | uniq | tr -d ':' >> meta
awk -F: '{print $1}' rpm-desktop |  uniq >> meta


cd tmp_rpms

awk -F/  '{print $0 " && rpm2cpio " $NF "| cpio -id && rm " $NF}' ../meta | sed -e "s|^|wget -nv ${uri}|" > cmd

echo 'start to download and cpio the rpm'
sh ./cmd
echo 'finished'

cd ..
mkdir database
mv tmp_rpms/usr/share/applications/ database
mv tmp_rpms/usr/share/icons/ database
mv tmp_rpms/usr/share/pixmaps/ database

rm -fr tmp_rpms
rm ARCHIVE

mkdir icons
make
./appdata_create
rm -fr database
